//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Admin
{
    public Admin()
    {
        this.Question = new HashSet<Question>();
    }

    public int AdminId { get; set; }
    public string AdminName { get; set; }
    public string AdminPassword { get; set; }
    public string AdminImage { get; set; }
    public string AdminEmail { get; set; }
    public bool Flag { get; set; }

    public virtual ICollection<Question> Question { get; set; }
}

public partial class Application
{
    public int ApplicationId { get; set; }
    public string Name { get; set; }
    public bool Sex { get; set; }
    public string Major { get; set; }
    public string Telephone { get; set; }
    public string Department { get; set; }
    public string QQ { get; set; }
    public string Introdution { get; set; }
    public System.DateTime Time { get; set; }
    public string Grade { get; set; }
}

public partial class Event
{
    public int EventId { get; set; }
    public string EventContent { get; set; }
    public string EventImage { get; set; }
    public string EventTime { get; set; }
}

public partial class Member
{
    public int MemberId { get; set; }
    public string MemberName { get; set; }
    public string MemberImage { get; set; }
    public string MemberDepartment { get; set; }
    public string MemberGrade { get; set; }
    public string MemberYear { get; set; }
    public string MemberInstruction { get; set; }
    public string MemberInterest { get; set; }
}

public partial class Message
{
    public int MessageId { get; set; }
    public string MessageContent { get; set; }
    public string MessageComment { get; set; }
    public string MessageAdminName { get; set; }
    public System.DateTime MessageTime { get; set; }
    public string MessagePhoto { get; set; }
}

public partial class Question
{
    public int QuestionId { get; set; }
    public int AdminId { get; set; }
    public string Question1 { get; set; }
    public string Answer { get; set; }

    public virtual Admin Admin { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Works
{
    public int WorksId { get; set; }
    public string WorksName { get; set; }
    public string WorksUrl { get; set; }
    public string WorksImage { get; set; }
    public System.DateTime WorksTime { get; set; }
}
