//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ITShowEntities : DbContext
{
    public ITShowEntities()
        : base("name=ITShowEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Admin> Admin { get; set; }
    public DbSet<Application> Application { get; set; }
    public DbSet<Event> Event { get; set; }
    public DbSet<Message> Message { get; set; }
    public DbSet<Question> Question { get; set; }
    public DbSet<sysdiagrams> sysdiagrams { get; set; }
    public DbSet<Works> Works { get; set; }
    public DbSet<Member> Member { get; set; }
}
